#!/bin/bash

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Variables
PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_PROJECT_PATH="${SHARED_PROJECT_PATH:-$PROJECT_PATH/../Shared}"
PUBLISH_DIR="$PROJECT_PATH/bin/publish"
ZIP_FILE="$PROJECT_PATH/RequestAPI.zip"
# These can be overridden from the calling environment (e.g. deployment/RequestAPI/deploy.sh)
RESOURCE_GROUP="${REQUESTAPI_RESOURCE_GROUP:-${RESOURCE_GROUP:-nvmrequestapi}}"
FUNCTION_APP="${REQUESTAPI_FUNCTION_APP:-${FUNCTION_APP:-nvmrequestapi}}"

# Function to log messages
log() {
    local level=$1
    shift
    local message=$@
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    case $level in
        "INFO") echo -e "${GREEN}[INFO]${NC} $timestamp - $message" ;;
        "WARN") echo -e "${YELLOW}[WARN]${NC} $timestamp - $message" ;;
        "ERROR") echo -e "${RED}[ERROR]${NC} $timestamp - $message" ;;
    esac
}

# Function to check if a command exists
check_command() {
    if ! command -v $1 &> /dev/null; then
        log "ERROR" "$1 is required but not installed."
        exit 1
    fi
}

# Check required commands
check_command "dotnet"
check_command "az"
check_command "zip"
check_command "unzip"

# Verify Azure CLI login
log "INFO" "Verifying Azure CLI login..."
if ! az account show &> /dev/null; then
    log "ERROR" "Not logged into Azure CLI. Please run 'az login' first."
    exit 1
fi

# Determine if we can skip the build/package step by checking whether the
# existing zip file is newer than all relevant source files.
SKIP_BUILD=false
if [ -f "$ZIP_FILE" ]; then
    log "INFO" "Existing deployment package found. Checking if rebuild is needed..."
    # Find any source file (in this project or the Shared project) that is
    # newer than the zip file. Excludes build output directories.
    NEWER_FILE=$(find "$PROJECT_PATH" "$SHARED_PROJECT_PATH" \
        -type d \( -name bin -o -name obj -o -name publish -o -name .azure \) -prune -o \
        -type f \( -name "*.cs" -o -name "*.csproj" -o -name "*.json" -o -name "*.config" \) \
        -newer "$ZIP_FILE" -print 2>/dev/null | head -n 1)

    if [ -z "$NEWER_FILE" ]; then
        log "INFO" "Existing zip is newer than all source files. Skipping build and package steps."
        SKIP_BUILD=true
    else
        log "INFO" "Source file newer than zip detected ($NEWER_FILE). Rebuilding..."
    fi
fi

if [ "$SKIP_BUILD" = false ]; then

# Clean previous publish
log "INFO" "Cleaning previous build artifacts..."
rm -rf "$PUBLISH_DIR"
rm -f "$ZIP_FILE"

# Create a project.assets.json file to specify the function app runtime version
log "INFO" "Configuring project for Flex Consumption..."
mkdir -p "$PROJECT_PATH/.azure"
cat > "$PROJECT_PATH/.azure/config.json" << EOLINNER
{
  "app": {
    "isFlexConsumption": true,
    "language": "dotnet-isolated",
    "runtime": "dotnet-isolated|9.0"
  }
}
EOLINNER

# Build the Shared project
log "INFO" "Building Shared project..."
if ! dotnet build "$SHARED_PROJECT_PATH/Shared.csproj" -c Release; then
    log "ERROR" "Failed to build Shared project"
    exit 1
fi

# Clean and build the main project first
log "INFO" "Building RequestAPI project..."
if ! dotnet clean "$PROJECT_PATH/RequestAPI.csproj" -c Release; then
    log "ERROR" "Failed to clean RequestAPI project"
    exit 1
fi

if ! dotnet build "$PROJECT_PATH/RequestAPI.csproj" -c Release; then
    log "ERROR" "Failed to build RequestAPI project"
    exit 1
fi

# Check for required build output files
if [ ! -f "$PROJECT_PATH/bin/Release/net9.0/RequestAPI.dll" ] || \
   [ ! -f "$PROJECT_PATH/bin/Release/net9.0/RequestAPI.deps.json" ] || \
   [ ! -f "$PROJECT_PATH/bin/Release/net9.0/RequestAPI.runtimeconfig.json" ]; then
    log "ERROR" "Required build output files are missing"
    exit 1
fi

# Publish the project
log "INFO" "Publishing RequestAPI project..."
if ! dotnet publish "$PROJECT_PATH/RequestAPI.csproj" -c Release -o "$PUBLISH_DIR" --no-build; then
    log "ERROR" "Failed to publish RequestAPI project"
    exit 1
fi

# Verify publish output
log "INFO" "Verifying publish output..."
if [ ! -f "$PUBLISH_DIR/RequestAPI.dll" ] || \
   [ ! -f "$PUBLISH_DIR/RequestAPI.deps.json" ] || \
   [ ! -f "$PUBLISH_DIR/RequestAPI.runtimeconfig.json" ]; then
    log "ERROR" "Required files missing in publish directory"
    exit 1
fi

# Copy configuration files
log "INFO" "Copying configuration files..."
if ! cp "$PROJECT_PATH/host.json" "$PUBLISH_DIR/host.json"; then
    log "ERROR" "Failed to copy host.json"
    exit 1
fi

# Verify functions.metadata was generated by the Worker SDK during publish.
# For .NET isolated, this file is generated automatically and lists all
# discovered [Function] methods. If it is missing, the worker has nothing
# to host and Flex will loop on "Failed to start language worker process".
# Do NOT hand-write function.json files or .azurefunctions directories on
# isolated worker — that is in-process style and breaks the Flex worker.
if [ ! -f "$PUBLISH_DIR/functions.metadata" ]; then
    log "ERROR" "functions.metadata not produced by 'dotnet publish'. Worker SDK may not be referenced correctly."
    exit 1
fi

log "INFO" "functions.metadata contents:"
cat "$PUBLISH_DIR/functions.metadata"

# Create deployment package
log "INFO" "Creating deployment package..."
cd "$PUBLISH_DIR" || exit 1
if ! zip -r "$ZIP_FILE" . -x "*.pdb" "*.xml"; then
    log "ERROR" "Failed to create deployment package"
    cd "$PROJECT_PATH"
    exit 1
fi
cd "$PROJECT_PATH"

# Verify package contents
log "INFO" "Verifying deployment package..."
if ! unzip -l "$ZIP_FILE" | grep -q "host.json"; then
    log "ERROR" "Deployment package verification failed - missing host.json"
    exit 1
fi

if ! unzip -l "$ZIP_FILE" | grep -q "RequestAPI.dll"; then
    log "ERROR" "Deployment package verification failed - missing RequestAPI.dll"
    exit 1
fi

if ! unzip -l "$ZIP_FILE" | grep -q "functions.metadata"; then
    log "ERROR" "Deployment package verification failed - missing functions.metadata"
    exit 1
fi

fi  # end of if [ "$SKIP_BUILD" = false ]

# Check if function app exists
log "INFO" "Verifying function app exists..."
if ! az functionapp show --name "$FUNCTION_APP" --resource-group "$RESOURCE_GROUP" &> /dev/null; then
    log "ERROR" "Function app $FUNCTION_APP not found in resource group $RESOURCE_GROUP"
    exit 1
fi

# Deploy to Azure Flex Consumption. Deployment storage auth is configured by
# deployment/RequestAPI/create.sh so this works even when storage local auth is
# disabled by policy.
log "INFO" "Deploying to Azure Functions Flex Consumption..."
set +e
DEPLOY_OUTPUT=$(az functionapp deployment source config-zip \
    --resource-group "$RESOURCE_GROUP" \
    --name "$FUNCTION_APP" \
    --src "$ZIP_FILE" 2>&1)
DEPLOY_RC=$?
set -e
echo "$DEPLOY_OUTPUT"

if [ "$DEPLOY_RC" -ne 0 ]; then
    if echo "$DEPLOY_OUTPUT" | grep -q "Failed to fetch host key" && \
        az functionapp function list --resource-group "$RESOURCE_GROUP" --name "$FUNCTION_APP" --query "[].name" -o tsv 2>/dev/null | grep -q .; then
        log "WARN" "Package deployment completed, but Azure CLI could not fetch a host key for its post-deploy health check. Functions are visible in Azure."
    else
        log "ERROR" "Deployment failed"
        exit 1
    fi
else
    log "INFO" "Deployment completed successfully"
fi

# Verify deployment
log "INFO" "Verifying deployment..."
sleep 10  # Wait for deployment to stabilize
APP_STATE=$(az functionapp show --name "$FUNCTION_APP" --resource-group "$RESOURCE_GROUP" --query "state" -o tsv 2>/dev/null || true)
if [ "$APP_STATE" = "Running" ]; then
    log "INFO" "Function app is running."
elif az functionapp function list --name "$FUNCTION_APP" --resource-group "$RESOURCE_GROUP" --query "[].name" -o tsv 2>/dev/null | grep -q .; then
    log "INFO" "Deployed functions are visible in Azure."
else
    log "WARN" "Function app may not be running properly. Please check the Azure portal"
fi
