#!/bin/bash

# =============================================================================
# Derived/Computed Values for SimpleL7Proxy Deployment
# =============================================================================
# This file is auto-sourced by deploy.sh and other scripts.
# Do NOT edit this file — it is derived from deploy.parameters.sh.
# =============================================================================

# Registry server FQDN
export REGISTRY_SERVER="${ACR_NAME}.azurecr.io"

# Resolve repository root relative to this script
_DERIVED_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" 2>/dev/null && pwd)"
_REPO_ROOT="${_DERIVED_DIR}/.."

# Extract proxy version from Constants.cs
if [ -f "${_REPO_ROOT}/src/SimpleL7Proxy/Constants.cs" ]; then
    _PROXY_VERSION_FROM_CODE=$(grep -oP 'VERSION = "\K[^"]+' "${_REPO_ROOT}/src/SimpleL7Proxy/Constants.cs" 2>/dev/null || echo "")
    if [ -n "${_PROXY_VERSION_FROM_CODE}" ] && [[ ! ${_PROXY_VERSION_FROM_CODE} == v* ]]; then
        _PROXY_VERSION_FROM_CODE="v${_PROXY_VERSION_FROM_CODE}"
    fi
fi

# Extract health probe version from Constants.cs
if [ -f "${_REPO_ROOT}/src/HealthProbe/Constants.cs" ]; then
    _HEALTHPROBE_VERSION_FROM_CODE=$(grep -oP 'VERSION = "\K[^"]+' "${_REPO_ROOT}/src/HealthProbe/Constants.cs" 2>/dev/null || echo "")
    if [ -n "${_HEALTHPROBE_VERSION_FROM_CODE}" ] && [[ ! ${_HEALTHPROBE_VERSION_FROM_CODE} == v* ]]; then
        _HEALTHPROBE_VERSION_FROM_CODE="v${_HEALTHPROBE_VERSION_FROM_CODE}"
    fi
fi

# Final versions: override > extracted > fallback
export PROXY_VERSION="${PROXY_VERSION_OVERRIDE:-${_PROXY_VERSION_FROM_CODE:-v1.0.0}}"
export HEALTHPROBE_VERSION="${HEALTHPROBE_VERSION_OVERRIDE:-${_HEALTHPROBE_VERSION_FROM_CODE:-v1.0.0}}"

# Full image references
export PROXY_IMAGE="${REGISTRY_SERVER}/${PROXY_IMAGE_NAME}:${PROXY_VERSION}"
export HEALTH_IMAGE="${REGISTRY_SERVER}/${HEALTH_IMAGE_NAME}:${HEALTHPROBE_VERSION}"

# Backwards-compat aliases (legacy variable names used by some scripts)
export WEB_IMAGE="${PROXY_IMAGE}"
export IMAGE_NAME="${PROXY_IMAGE}"
