@export()
type DeploymentSettings = {
  PRIVATE_NETWORK_DEPLOYMENT: bool
  ASYNC_DEPLOYMENT: bool
  LOCATION: string
  RESOURCE_GROUPS: string[]
  NETWORK_RESOURCE_GROUP: string
  CONTAINER_APP_RESOURCE_GROUP: string
  STORAGE_RESOURCE_GROUP: string
  APPCONFIG_RESOURCE_GROUP: string
  REQUESTAPI_RESOURCE_GROUP: string
  SERVICEBUS_RESOURCE_GROUP: string
  COSMOS_RESOURCE_GROUP: string
  ACR_NAME: string
  ACR_SKU: 'Basic' | 'Standard' | 'Premium'
  PROXY_IMAGE_NAME: string
  HEALTH_IMAGE_NAME: string
  CONTAINER_APP_NAME: string
  MIN_REPLICAS: int
  MAX_REPLICAS: int
  ENABLE_MANAGED_IDENTITY: bool
  ENABLE_APP_INSIGHTS: bool
  LOG_ANALYTICS_WORKSPACE_NAME: string
  ENVIRONMENT_NAME: string
  WEB_CPU: string
  WEB_MEMORY: string
  HEALTH_CPU: string
  HEALTH_MEMORY: string
  WEB_PORT: int
  HEALTH_PORT: int
  INGRESS_TYPE: 'external' | 'internal'
  ENABLE_HTTPS: bool
  REVISION_MODE: 'single' | 'multiple'
  TERMINATION_GRACE_PERIOD_SECONDS: int
  HEALTHPROBE_TYPE: 'sidecar' | 'internal'
  APPCONFIG_NAME: string
  APPCONFIG_SKU: 'standard' | 'free'
  APPCONFIG_LABEL: string
  AZURE_APPCONFIG_REFRESH_INTERVAL_SECONDS: int
  UPDATE_CONTAINER_APP_ENV: bool
  VNET_NAME: string
  VNET_ADDRESS_PREFIX: string
  SUBNET_ACA_NAME: string
  SUBNET_ACA_PREFIX: string
  SUBNET_CLIENTVM_NAME: string
  SUBNET_CLIENTVM_PREFIX: string
  SUBNET_AZUREFUNCTIONS_NAME: string
  SUBNET_AZUREFUNCTIONS_PREFIX: string
  SUBNET_APIM_NAME: string
  SUBNET_APIM_PREFIX: string
  SUBNET_PRIVATEENDPOINTS_NAME: string
  SUBNET_PRIVATEENDPOINTS_PREFIX: string
  DISABLE_PRIVATE_ENDPOINT_NETWORK_POLICIES: bool
  DNS_ZONE_NAME: string
  ACA_INTERNAL_FQDN: string
  ACA_RECORD_NAME: string
  APIM_PRIVATE_IP: string
  APIM_RECORD_NAME: string
  STORAGE_ACCOUNT_NAME: string
  STORAGE_SKU: 'Standard_LRS' | 'Standard_GRS' | 'Standard_ZRS' | 'Standard_RAGRS'
  CREATE_CONTAINERS: bool
  BLOB_CONTAINERS: string[]
  CA_BLOB_ROLE: string
  REQUESTAPI_FUNCTION_APP: string
  REQUESTAPI_LOCATION: string
  REQUESTAPI_STORAGE_ACCOUNT: string
  REQUESTAPI_APPINSIGHTS_NAME: string
  REQUESTAPI_RUNTIME_NAME: string
  REQUESTAPI_RUNTIME_VERSION: string
  REQUESTAPI_INSTANCE_MEMORY_MB: int
  REQUESTAPI_MAX_INSTANCE_COUNT: int
  REQUESTAPI_SERVICEBUS_NAMESPACE: string
  REQUESTAPI_SERVICEBUS_QUEUE: string
  REQUESTAPI_SERVICEBUS_FEEDER_QUEUE: string
  REQUESTAPI_COSMOS_ACCOUNT: string
  REQUESTAPI_COSMOS_DATABASE: string
  REQUESTAPI_COSMOS_CONTAINER: string
}
